### ISSUE TITLE
please add listener for change height of bottom sheet

### ISSUE THREAD

**Issue by behnam-maqsudi** [woofers/react-sheet-slide#3]
hello. can you add some props for changing current detent? 
and can you add a prop for disabling backdrop animation when toggle bottom sheet?

**Comment by woofers** [comment]
@benamm 

To disable the backdrop animation you can add the following CSS:

```css
.rss-backdrop {
  clip-path: none;
  transform: none;
  padding-top: 0;
}
```

Currently you can't change the `selectedDetent` while the sheet is open, however you can when its closed.  PR are welcome if your are interested in this feature.
