### ISSUE TITLE
How to disable background resize

### ISSUE THREAD

**Issue by ejabu** [woofers/react-sheet-slide#6]
<img width="505" alt="image" src="https://github.com/woofers/react-sheet-slide/assets/2019630/bdcc37e9-a740-47c6-a258-751c02da5534">

when the modal is opened, the backround is having animated resizing.

In older devices, it has some lags.

I was wondering how can we disabled it ?

So the experience pretty much the same with `react-spring-bottom-sheet`.

best regards,

**Comment by ejabu** [comment]
Should we add something like this below ?

<img width="867" alt="image" src="https://github.com/woofers/react-sheet-slide/assets/2019630/0cfd3e97-1bbc-4870-8ee7-8572960cf05d">

**Comment by woofers** [comment]
@ejabu I'm hesitant to add too many props to control the look of the sheet since there are many variations users may want.  

Instead you should just be able to adjust the CSS or remove `.rss-backdrop` class on the content of your site, since this is what applies that animation.

Alternatively you can just add some CSS to target that class and override the animation:

```css
.rss-backdrop {
  padding-top: 0;
  transform: none;
  clip-path: none;
} 
```

<img src="https://github.com/woofers/react-sheet-slide/assets/7284672/55ebe717-3482-4f92-a77a-631121b16bb9" width="200">


Either should work but the first solution will also disable the backdrop fade animation, while the second will remove only the scale animation, but keep the contrast adjust on the backdrop.

Let me know if this resolves your issue.

**Comment by ejabu** [comment]
@woofers thanks for helping me out !

I think the solution works. its very nice to have this cool workaround. 

<img width="715" alt="image" src="https://github.com/woofers/react-sheet-slide/assets/2019630/e7d9eb0e-e1db-4cfa-a4a0-1b3892ad7364">


```css
.rss-backdrop {
  padding-top: 0 !important;
  transform: none !important;
  clip-path: none !important;
} 
```
